import { describe, expect, it, vi } from "vitest";
import {
  BindingError,
  CODE_BRIDGE_UNAVAILABLE,
  CODE_CALL_FAILED,
  CODE_MALFORMED_RESPONSE,
  CODE_UNKNOWN,
  call,
  isBindingError,
} from "./call";
import { health } from "./index";
import { installMethod as installBridge } from "./testing";
import { MESSAGES } from "@/i18n/messages";
import fixture from "./__fixtures__/envelope.contract.json";

describe("call — the single unwrap point", () => {
  it("returns data on ok", async () => {
    installBridge("System", "Health", () =>
      Promise.resolve({ ok: true, data: { version: "1.2.3" } }),
    );
    await expect(call("System", "Health")).resolves.toEqual({ version: "1.2.3" });
  });

  it("throws BindingError carrying code and params on failure", async () => {
    installBridge("System", "Health", () =>
      Promise.resolve({
        ok: false,
        data: null,
        error: {
          code: "migrate.database_too_new",
          messageKey: "migrate.database_too_new",
          params: { current: "5", target: "3" },
        },
      }),
    );

    const err = await call("System", "Health").catch((e: unknown) => e);
    expect(isBindingError(err)).toBe(true);
    const be = err as BindingError;
    expect(be.code).toBe("migrate.database_too_new");
    expect(be.messageKey).toBe("migrate.database_too_new");
    expect(be.params).toEqual({ current: "5", target: "3" });
  });

  it("passes arguments through to the bound method", async () => {
    const spy = vi.fn(() => Promise.resolve({ ok: true, data: [] }));
    installBridge("Ops", "Runs", spy);
    await call("Ops", "Runs", "platform.heartbeat", 10);
    expect(spy).toHaveBeenCalledWith("platform.heartbeat", 10);
  });

  it("surfaces an absent bridge as a typed error, not a crash", async () => {
    // No window.go, and no mock registered for this struct.
    const err = await call("Nonexistent", "Method").catch((e: unknown) => e);
    expect(isBindingError(err)).toBe(true);
    expect((err as BindingError).code).toBe(CODE_BRIDGE_UNAVAILABLE);
  });

  it("surfaces a malformed response as a typed error", async () => {
    installBridge("System", "Health", () => Promise.resolve({ version: "1.2.3" }));
    const err = await call("System", "Health").catch((e: unknown) => e);
    expect((err as BindingError).code).toBe(CODE_MALFORMED_RESPONSE);
  });

  it("surfaces an IPC failure as a typed error without leaking developer text", async () => {
    installBridge("System", "Health", () => Promise.reject(new Error("some internal go text")));
    const err = await call("System", "Health").catch((e: unknown) => e);
    expect((err as BindingError).code).toBe(CODE_CALL_FAILED);
    expect(JSON.stringify(err)).not.toContain("some internal go text");
  });

  it("tolerates a failure result with no error object", async () => {
    installBridge("System", "Health", () => Promise.resolve({ ok: false, data: null }));
    const err = await call("System", "Health").catch((e: unknown) => e);
    expect((err as BindingError).code).toBe(CODE_UNKNOWN);
  });
});

describe("the Step 0.11 §1.2 regression drill", () => {
  /**
   * THE test this step exists for.
   *
   * Step 0.10 wrapped App.Health() in Result[T]; the frontend wrapper kept declaring the
   * pre-0.10 flat shape, so `health.version` was undefined and the shell rendered "…" forever
   * in the packaged app. `make ci` was green throughout.
   *
   * Mutation check: make `call` return the envelope instead of `raw.data` and this fails.
   */
  it("renders a real version from an envelope-shaped Health response", async () => {
    installBridge("System", "Health", () => Promise.resolve(fixture.healthOk));

    const info = await health();

    expect(info.version).toBe("1.2.3");
    expect(info.platform).toBe("darwin/arm64");
    // The exact failure that shipped: an envelope leaking through as the payload.
    expect(info).not.toHaveProperty("ok");
    expect(info).not.toHaveProperty("data");
  });

  /**
   * The second half of the same defect: `data,omitempty` omitted empty slices, so a list
   * binding with zero rows arrived as undefined and crashed on .map().
   */
  it("returns [] for an empty list rather than undefined", async () => {
    installBridge("Money", "Currencies", () => Promise.resolve(fixture.emptyListOk));
    const result = await call<string[]>("Money", "Currencies");
    expect(result).toEqual([]);
    expect(() => result.map((c) => c)).not.toThrow();
  });
});

describe("cross-language contract", () => {
  // The fixture is generated by internal/api/envelope/contract_test.go. If the Go envelope
  // changes shape, that test fails first; regenerating it then fails these until the wrapper
  // is updated. Neither side can move alone (§3.3).

  it("unwraps every success sample the Go side produces", async () => {
    installBridge("X", "Y", () => Promise.resolve(fixture.listOk));
    await expect(call("X", "Y")).resolves.toEqual(["SYP", "USD"]);
  });

  it("maps a typed Go failure to a BindingError with params", async () => {
    installBridge("X", "Y", () => Promise.resolve(fixture.typedFailure));
    const err = (await call("X", "Y").catch((e: unknown) => e)) as BindingError;
    expect(err.code).toBe("migrate.database_too_new");
    expect(err.params.current).toBe("5");
  });

  it("maps a Go validation failure's field errors", async () => {
    installBridge("X", "Y", () => Promise.resolve(fixture.validationFailure));
    const err = (await call("X", "Y").catch((e: unknown) => e)) as BindingError;
    expect(err.fields).toHaveLength(1);
    expect(err.fields[0]).toMatchObject({ field: "locale", code: "i18n.invalid_locale" });
  });

  it("never receives developer prose from an untyped Go error", async () => {
    installBridge("X", "Y", () => Promise.resolve(fixture.untypedFailure));
    const err = (await call("X", "Y").catch((e: unknown) => e)) as BindingError;
    expect(err.code).toBe("database.internal");
    expect(JSON.stringify(fixture.untypedFailure)).not.toContain("some internal go text");
  });
});

describe("frontend-produced error codes are translatable", () => {
  /**
   * The frontend mirror of Step 0.8's error-code coverage gate.
   *
   * Go codes are covered by the AST walk in the Go test suite. These four originate here, so
   * without this gate a transport failure would render as raw `app.bridge_unavailable` — the
   * exact outcome the Go gate exists to prevent.
   */
  const CODES = [
    CODE_BRIDGE_UNAVAILABLE,
    CODE_CALL_FAILED,
    CODE_MALFORMED_RESPONSE,
    CODE_UNKNOWN,
  ];

  for (const locale of Object.keys(MESSAGES)) {
    it(`every code has a ${locale} translation`, () => {
      const missing = CODES.filter((code) => !MESSAGES[locale as "en" | "ar"][code]);
      expect(missing).toEqual([]);
    });
  }
});
