import { describe, expect, it } from "vitest";
import { mockInvoke } from "./mock";
import type { Result } from "./types";
import fixture from "./__fixtures__/envelope.contract.json";

/**
 * The dev mock must satisfy the same contract as the real bridge.
 *
 * Step 0.11 §1.2, lesson 1: the previous mock returned the pre-envelope flat shape, so
 * `npm run dev` looked correct while the packaged app was broken. A mock that does not match
 * the contract actively certifies the failing path, which is worse than having no mock.
 */
describe("the browser-dev mock", () => {
  it("returns a genuine envelope, not a bare payload", async () => {
    const invoke = mockInvoke("System", "Health");
    expect(invoke).toBeDefined();

    const result = (await invoke!()) as Result<unknown>;
    expect(result).toHaveProperty("ok", true);
    expect(result).toHaveProperty("data");
  });

  it("produces the same field set as the Go type", async () => {
    // The fixture is generated by internal/api/envelope/contract_test.go, so this compares
    // the mock against the real serialised shape rather than against a hand-copied list.
    const result = (await mockInvoke("System", "Health")!()) as Result<
      Record<string, unknown>
    >;
    const goFields = Object.keys(fixture.healthOk.data).sort();
    expect(Object.keys(result.data).sort()).toEqual(goFields);
  });

  it("returns an array for every list binding", async () => {
    for (const [struct, method] of [
      ["Ops", "Jobs"],
      ["Ops", "Runs"],
      ["Money", "Currencies"],
      ["Audit", "Entries"],
    ] as const) {
      const result = (await mockInvoke(struct, method)!()) as Result<unknown>;
      expect(Array.isArray(result.data), `${struct}.${method}`).toBe(true);
    }
  });

  it("has no mock for an unknown struct, so call() reports it as unavailable", () => {
    expect(mockInvoke("Nonexistent", "Method")).toBeUndefined();
  });
});
