package printing_test

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mizan-erp/mizan/internal/kernel/errs"
	"github.com/mizan-erp/mizan/internal/platform/printing"
)

// -update rewrites the golden files.
//
// A flag rather than an environment variable, because `go test -update` appears in the command
// somebody actually ran and an environment variable does not — and a golden file regenerated by
// accident is a test that has agreed with a defect.
var update = flag.Bool("update", false, "rewrite the golden files")

func simpleTemplate() printing.Template {
	return printing.Template{
		Code: "receipt", Media: "receipt",
		Blocks: []printing.Block{
			{Kind: printing.Text, Text: "{company}", Align: printing.Center, Bold: true},
			{Kind: printing.Text, Text: "{branch}", Align: printing.Center, OmitWhenEmpty: true},
			{Kind: printing.Rule},
			{Kind: printing.Pair, Text: "Invoice", Value: "{number}"},
			{Kind: printing.Rows, Columns: []printing.Column{
				{Field: "item", Header: "Item", Align: printing.Start, Width: 60},
				{Field: "total", Header: "Amount", Align: printing.End, Width: 40},
			}},
			{Kind: printing.Rule},
			{Kind: printing.Pair, Text: "TOTAL", Value: "{total}", Bold: true, Large: true},
		},
	}
}

func simpleData() printing.Data {
	return printing.Data{
		Fields: map[string]string{
			"company": "Al Noor Trading", "branch": "", "number": "INV-0042", "total": "1,234.50",
		},
		Rows: []map[string]string{
			{"item": "Bag of cement", "total": "34.50"},
			{"item": "Steel rod 12mm", "total": "1,200.00"},
		},
		Direction: "ltr",
	}
}

// ── resolution ──────────────────────────────────────────────────────────────────

func TestAMissingFieldIsRefusedRatherThanPrintedBlank(t *testing.T) {
	// A placeholder nobody supplied is a template referring to something that does not exist.
	// Guessing produces a receipt with a blank where the total should be — handed to a customer
	// with the drawer already open, and not noticed until somebody complains.
	template := simpleTemplate()
	data := simpleData()
	delete(data.Fields, "total")

	_, err := printing.Render(template, data)
	if err == nil {
		t.Fatal("a template referring to a field the document does not have was accepted")
	}
	if code := errs.CodeOf(err); code != printing.CodeUnknownField {
		t.Fatalf("code = %q, want %q", code, printing.CodeUnknownField)
	}
}

func TestAnOptionalBlockIsDroppedRatherThanLeftBlank(t *testing.T) {
	// One template must serve a shop with branches and a shop with one shopfront. The
	// alternative is a template per configuration, which is the per-country forking this
	// product exists to avoid — and a blank line where a branch name would go is a receipt that
	// looks broken.
	document, err := printing.Render(simpleTemplate(), simpleData())
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	for _, block := range document.Blocks {
		if block.Kind == printing.Text && block.Text == "" {
			t.Fatal("an empty optional block survived into the document")
		}
	}

	// And it comes BACK when the field is supplied — otherwise "dropped" could just mean
	// "never rendered".
	data := simpleData()
	data.Fields["branch"] = "Sharjah Road"
	document, err = printing.Render(simpleTemplate(), data)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(renderedText(document), "Sharjah Road") {
		t.Fatal("a supplied optional field did not appear")
	}
}

func TestALiteralIsNotTreatedAsOptional(t *testing.T) {
	// "Thank you for your custom" has no placeholders and is not conditional on anything.
	// Treating "no placeholder resolved" as "nothing to print" would silently delete every
	// fixed line on the receipt.
	template := printing.Template{Code: "t", Media: "receipt", Blocks: []printing.Block{
		{Kind: printing.Text, Text: "Thank you", OmitWhenEmpty: true},
	}}
	document, err := printing.Render(template, printing.Data{Fields: map[string]string{}})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if len(document.Blocks) != 1 {
		t.Fatalf("the literal was dropped: %+v", document.Blocks)
	}
}

func TestAnUnclosedPlaceholderIsRefused(t *testing.T) {
	// A typo in a file an administrator edited. Printing it literally puts "{total" on a
	// customer's receipt.
	template := printing.Template{Code: "t", Media: "receipt", Blocks: []printing.Block{
		{Kind: printing.Text, Text: "Total: {total"},
	}}
	_, err := printing.Render(template, printing.Data{Fields: map[string]string{"total": "1"}})
	if errs.CodeOf(err) != printing.CodeBadTemplate {
		t.Fatalf("err = %v, want %s", err, printing.CodeBadTemplate)
	}
}

func TestArabicIndicDigitsConvertWithoutTouchingSeparators(t *testing.T) {
	// §22.5: the numeral system is configurable and varies by COUNTRY AND BY CUSTOMER, so it is
	// not inferred from the language — an Arabic invoice from a Gulf exporter usually carries
	// Western digits.
	//
	// Only the digits change. The grouping and decimal marks were chosen by a formatter that
	// had the currency in front of it, and re-deciding them here would overrule it.
	data := simpleData()
	data.Digits = "arabic"

	document, err := printing.Render(simpleTemplate(), data)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	text := renderedText(document)

	if !strings.Contains(text, "١,٢٣٤.٥٠") {
		t.Fatalf("digits were not converted, or separators were: %q", text)
	}
	if strings.Contains(text, "1,234.50") {
		t.Fatal("the Western form survived alongside the Arabic-Indic one")
	}
}

func TestWidthsAreSharesAndAreNormalised(t *testing.T) {
	// Templates are written by people, and people write widths that sum to 97. A column given
	// twice the share of another must keep twice the share whatever the total was.
	shares := printing.Widths([]printing.Cell{{Width: 20}, {Width: 40}, {Width: 37}}, 100)

	// EXACTLY 100. The ESC/POS renderer turns shares into character counts, so shares summing
	// to 99 lay a 48-column receipt out across 47 and leave every amount one character short of
	// the edge, forever.
	if sum(shares) != 100 {
		t.Fatalf("shares sum to %d, want 100: %v", sum(shares), shares)
	}
	// Integer shares cannot double exactly, but the ORDER must survive: a column declared wider
	// than another must not come out narrower.
	if !(shares[1] > shares[2] && shares[2] > shares[0]) {
		t.Fatalf("the declared order was not preserved: %v", shares)
	}
	if shares[1] < 40 || shares[1] > 42 {
		t.Fatalf("40/97 should be about 41%%, got %d", shares[1])
	}

	// Three columns and no declared widths: 100 does not divide by 3, and the point must still
	// land somewhere rather than being dropped.
	thirds := printing.Widths([]printing.Cell{{}, {}, {}}, 100)
	if sum(thirds) != 100 {
		t.Fatalf("undeclared widths lost a point: %v", thirds)
	}

	// No widths at all: shared evenly rather than collapsed to zero, which would swallow every
	// column's contents.
	even := printing.Widths([]printing.Cell{{}, {}, {}, {}}, 100)
	for _, share := range even {
		if share != 25 {
			t.Fatalf("undeclared widths did not share evenly: %v", even)
		}
	}

	// Allocated against CHARACTERS, which is what the ESC/POS renderer needs. Going via 100
	// would round twice, and the second rounding undoes the first.
	chars := printing.Widths([]printing.Cell{{Width: 60}, {Width: 40}}, 48)
	if sum(chars) != 48 {
		t.Fatalf("a 48-column table was laid out across %d: %v", sum(chars), chars)
	}
}

// ── the golden files ────────────────────────────────────────────────────────────

func TestGoldenRenderings(t *testing.T) {
	cases := []struct {
		name   string
		render func() ([]byte, error)
	}{
		{"receipt_ltr.html", func() ([]byte, error) {
			document, err := printing.Render(simpleTemplate(), simpleData())
			if err != nil {
				return nil, err
			}
			return []byte(printing.HTML(document,
				printing.HTMLOptions{Paper: "80mm", Title: "Receipt"})), nil
		}},
		{"receipt_rtl.html", func() ([]byte, error) {
			data := simpleData()
			data.Direction = "rtl"
			data.Digits = "arabic"
			data.Fields["company"] = "مؤسسة النور للتجارة"
			data.Rows = []map[string]string{
				{"item": "كيس إسمنت", "total": "34.50"},
				{"item": "حديد تسليح ١٢ مم", "total": "1,200.00"},
			}
			document, err := printing.Render(simpleTemplate(), data)
			if err != nil {
				return nil, err
			}
			return []byte(printing.HTML(document,
				printing.HTMLOptions{Paper: "80mm", Title: "إيصال"})), nil
		}},
		{"invoice_a4.html", func() ([]byte, error) {
			template := simpleTemplate()
			template.Media = "document"
			document, err := printing.Render(template, simpleData())
			if err != nil {
				return nil, err
			}
			return []byte(printing.HTML(document,
				printing.HTMLOptions{Paper: "A4", Title: "Invoice INV-0042"})), nil
		}},
		{"receipt_80mm.escpos", func() ([]byte, error) {
			document, err := printing.Render(simpleTemplate(), simpleData())
			if err != nil {
				return nil, err
			}
			return printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 48, Cut: true})
		}},
		{"receipt_58mm.escpos", func() ([]byte, error) {
			document, err := printing.Render(simpleTemplate(), simpleData())
			if err != nil {
				return nil, err
			}
			return printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 32})
		}},
	}

	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			got, err := test.render()
			if err != nil {
				t.Fatalf("render: %v", err)
			}
			compareGolden(t, test.name, got)
		})
	}
}

// ── the ESC/POS renderer ────────────────────────────────────────────────────────

func TestThePairLinePushesToOppositeEdges(t *testing.T) {
	document, err := printing.Render(simpleTemplate(), simpleData())
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	out, err := printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 32})
	if err != nil {
		t.Fatalf("ESCPOS: %v", err)
	}

	line := findLine(string(out), "Invoice")
	if !strings.HasSuffix(line, "INV-0042") {
		t.Fatalf("the value was not pushed to the edge: %q", line)
	}
	if len([]rune(line)) != 32 {
		t.Fatalf("the line is %d columns, want 32: %q", len([]rune(line)), line)
	}
}

func TestLargeTextGetsHalfTheColumns(t *testing.T) {
	// Double-width characters mean half as much fits. Getting this wrong wraps the total — the
	// one line on a receipt that must not wrap.
	template := printing.Template{Code: "t", Media: "receipt", Blocks: []printing.Block{
		{Kind: printing.Pair, Text: "TOTAL", Value: "1,234.50", Large: true},
	}}
	document, err := printing.Render(template, printing.Data{Fields: map[string]string{}})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	out, err := printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 32})
	if err != nil {
		t.Fatalf("ESCPOS: %v", err)
	}

	line := findLine(string(out), "TOTAL")
	if width := len([]rune(line)); width != 16 {
		t.Fatalf("large text used %d columns, want 16 (half of 32): %q", width, line)
	}
}

func TestALabelIsCutBeforeAValueIs(t *testing.T) {
	// A receipt line reading "TOT 1,234.50" is understood. One reading "TOTAL PAYABLE INC" is
	// not — and it is the amount the customer is checking.
	template := printing.Template{Code: "t", Media: "receipt", Blocks: []printing.Block{
		{Kind: printing.Pair, Text: "TOTAL PAYABLE INCLUDING TAX", Value: "1,234,567.89"},
	}}
	document, _ := printing.Render(template, printing.Data{Fields: map[string]string{}})
	out, err := printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 20})
	if err != nil {
		t.Fatalf("ESCPOS: %v", err)
	}
	if !strings.Contains(string(out), "1,234,567.89") {
		t.Fatalf("the value was truncated instead of the label: %q", out)
	}
}

func TestArabicIsRefusedRatherThanPrintedAsQuestionMarks(t *testing.T) {
	// ESC/POS text mode selects a single-byte code page, and no Arabic one is reliably present
	// — nor could it express contextual letter shaping. A receipt of mojibake looks like a
	// PRINTER FAULT, so somebody reprints it, and the second one is identical.
	data := simpleData()
	data.Fields["company"] = "مؤسسة النور"
	document, err := printing.Render(simpleTemplate(), data)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	_, err = printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 48})
	if errs.CodeOf(err) != printing.CodeUnsupported {
		t.Fatalf("err = %v, want %s", err, printing.CodeUnsupported)
	}
}

func TestNothingIsEmittedWhenTheScriptIsRefused(t *testing.T) {
	// The whole document is checked BEFORE a byte is written. A printer that has already
	// consumed half a receipt cannot be un-printed.
	data := simpleData()
	data.Rows = append(data.Rows, map[string]string{"item": "كيس إسمنت", "total": "5.00"})
	document, _ := printing.Render(simpleTemplate(), data)

	out, err := printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 48})
	if err == nil {
		t.Fatal("Arabic in a table cell was accepted")
	}
	if out != nil {
		t.Fatalf("%d bytes were produced alongside the refusal", len(out))
	}
}

func TestArabicIndicDigitsAreRefusedByTheTillPrinterToo(t *testing.T) {
	// They are exactly as unprintable as the script they belong to, and it would be easy to
	// check for letters and forget the numerals — which fails on the one line that matters.
	data := simpleData()
	data.Digits = "arabic"
	document, _ := printing.Render(simpleTemplate(), data)

	if _, err := printing.ESCPOS(document, printing.ESCPOSOptions{Columns: 48}); err == nil {
		t.Fatal("Arabic-Indic numerals were accepted by the ESC/POS renderer")
	}
}

// ── the HTML renderer ───────────────────────────────────────────────────────────

func TestTheHTMLIsSelfContained(t *testing.T) {
	// A shop's till prints during an internet outage. A stylesheet that failed to load is an
	// invoice with no layout, handed to a customer.
	document, _ := printing.Render(simpleTemplate(), simpleData())
	page := printing.HTML(document, printing.HTMLOptions{Paper: "A4"})

	for _, forbidden := range []string{"http://", "https://", "<script", "<img", "@import"} {
		if strings.Contains(page, forbidden) {
			t.Errorf("the page reaches outside itself: %q", forbidden)
		}
	}
}

func TestTheDirectionReachesTheMarkup(t *testing.T) {
	data := simpleData()
	data.Direction = "rtl"
	document, _ := printing.Render(simpleTemplate(), data)
	page := printing.HTML(document, printing.HTMLOptions{Paper: "80mm"})

	if !strings.Contains(page, `dir="rtl"`) {
		t.Fatal("an RTL document did not produce an RTL page")
	}
	// start/end, never left/right: one template must serve both directions.
	if strings.Contains(page, "text-align: left") || strings.Contains(page, "text-align: right") {
		t.Fatal("the stylesheet hard-codes a physical direction")
	}
}

func TestValuesAreEscaped(t *testing.T) {
	// A product name is user-entered text and reaches this renderer unchanged. "Widget <b>" must
	// print as itself, not as markup — and the same string reaches a PDF a customer keeps.
	data := simpleData()
	data.Fields["company"] = `Smith & Sons <Trading>`
	document, _ := printing.Render(simpleTemplate(), data)
	page := printing.HTML(document, printing.HTMLOptions{Paper: "A4"})

	if strings.Contains(page, "<Trading>") {
		t.Fatal("a user-entered value reached the page unescaped")
	}
	if !strings.Contains(page, "Smith &amp; Sons &lt;Trading&gt;") {
		t.Fatal("the escaped form is missing")
	}
}

func TestThermalPaperGetsThermalMargins(t *testing.T) {
	// 12mm of margin on an 80mm roll throws away a quarter of every line.
	document, _ := printing.Render(simpleTemplate(), simpleData())
	thermal := printing.HTML(document, printing.HTMLOptions{Paper: "80mm"})
	a4 := printing.HTML(document, printing.HTMLOptions{Paper: "A4"})

	// The @page rule specifically. Matching anywhere in the document would catch the `margin:
	// 0 auto` that centres the sheet, which is a different "auto" entirely.
	if !strings.Contains(thermal, "@page { size: 80mm auto; margin: 2mm; }") {
		t.Fatalf("a receipt roll was not given a continuous page height and thin margins")
	}
	if !strings.Contains(a4, "@page { size: A4; margin: 12mm; }") {
		t.Fatal("A4 was not given a fixed page and printable margins")
	}
}

// ── helpers ─────────────────────────────────────────────────────────────────────

func sum(values []int) int {
	total := 0
	for _, value := range values {
		total += value
	}
	return total
}

func renderedText(document printing.Document) string {
	var out strings.Builder
	for _, block := range document.Blocks {
		out.WriteString(block.Text + " " + block.Value + "\n")
		for _, row := range block.Rows {
			for _, cell := range row {
				out.WriteString(cell.Text + " ")
			}
			out.WriteString("\n")
		}
	}
	return out.String()
}

func findLine(text, containing string) string {
	for _, line := range strings.Split(text, "\n") {
		if strings.Contains(line, containing) {
			// Strip the ESC/POS control sequences so the assertion is about the LAYOUT, which
			// is what these tests are checking.
			return stripControls(line)
		}
	}
	return ""
}

// controls are the exact sequences the ESC/POS renderer emits, longest first.
//
// EXACT sequences rather than "skip N bytes after an escape", because ESC/POS commands are not
// all the same length — ESC a n is three bytes and GS V B n is four. The first version of this
// helper guessed one length for all of them, ate the "T" off a TOTAL line, and made the test
// report a layout defect that did not exist. A helper that silently consumes payload is worse
// than no helper: it makes the code look wrong.
var controls = strings.NewReplacer(
	"\x1d\x56\x42\x00", "", // GS V B 0 — cut
	"\x1b\x61\x00", "", // ESC a 0 — align start
	"\x1b\x61\x01", "", // ESC a 1 — align centre
	"\x1b\x61\x02", "", // ESC a 2 — align end
	"\x1b\x45\x01", "", // ESC E 1 — bold on
	"\x1b\x45\x00", "", // ESC E 0 — bold off
	"\x1d\x21\x11", "", // GS ! 0x11 — double width and height
	"\x1d\x21\x00", "", // GS ! 0 — normal
	"\x1b\x40", "", // ESC @ — initialise
)

func stripControls(line string) string {
	stripped := controls.Replace(line)
	// Anything left is a control this helper does not know about, and skipping it silently is
	// how the last bug happened. The test should see it.
	for _, r := range stripped {
		if r < 0x20 && r != '\t' {
			return stripped // caller's assertion will fail on it, visibly
		}
	}
	return stripped
}

func compareGolden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", name)

	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden (run `go test ./... -update` to create it): %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s differs from its golden file.\n"+
			"If the change is intended, review it and re-run with -update.\n"+
			"--- got ---\n%s\n--- want ---\n%s", name, preview(got), preview(want))
	}
}

func preview(data []byte) string {
	const limit = 900
	text := strings.ReplaceAll(string(data), "\x1b", "<ESC>")
	text = strings.ReplaceAll(text, "\x1d", "<GS>")
	if len(text) > limit {
		return text[:limit] + "\n…"
	}
	return text
}
