// Package guide ships the shop's guides inside the application (L8 D-L8.16): the Markdown written in docs/mizan_lite/guide,
// rendered to A4 PDF by Lite's own document renderer — the embedded Arabic font, the same bidi rules as every printout — so a
// shop with no internet and no PDF tool on its computer still has its guide, and can print it.
//
// The PDFs are generated by cmd/lite-guides and embedded; TestTheEmbeddedGuidesAreTheDocuments fails when a guide was edited
// and not regenerated.
package guide

import (
	"regexp"
	"strings"

	"github.com/mizan-erp/mizan/internal/lite/documents"
	"github.com/mizan-erp/mizan/internal/lite/typeset"
)

// Created is every guide's PDF creation date: fixed, so rendering the same text gives the same bytes.
const Created = "D:20260915000000Z"

var (
	link     = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)
	image    = regexp.MustCompile(`!\[[^\]]*\]\([^)]*\)`)
	emphasis = regexp.MustCompile("\\*\\*|__|`")
	// A run of Latin letters and digits — a figure, a key name (F9), a file name, a word — kept left to right inside Arabic
	// text, as every figure Lite prints is (D-L7.3). Without it "F9" reads "9F" and a date reverses.
	figureRun  = regexp.MustCompile("[A-Za-z0-9][A-Za-z0-9.,:/×%+_-]*")
	numbered   = regexp.MustCompile(`^(\d+)\.\s+(.*)$`)
	tableRule  = regexp.MustCompile(`^\|?\s*:?-{3,}`)
	htmlBreaks = regexp.MustCompile(`<br\s*/?>`)
)

// Render lays a guide's Markdown out as a Document: headings, paragraphs, bulleted and numbered lists, tables, quotes and rules.
// Images are left out — the PDF is for reading and printing; the Markdown keeps the screenshots. In a right-to-left guide every
// run of digits is isolated left to right, as every figure Lite prints is (D-L7.3).
func Render(markdown string, dir documents.Direction, footer string) documents.Document {
	doc := documents.Document{Direction: dir, Footer: footer, Meta: documents.Meta{Created: Created}}
	lines := strings.Split(strings.ReplaceAll(markdown, "\r\n", "\n"), "\n")
	var paragraph []string
	flush := func() {
		if len(paragraph) > 0 {
			doc.Blocks = append(doc.Blocks, documents.Paragraph{Text: inline(strings.Join(paragraph, " "), dir)})
			paragraph = nil
		}
	}
	for i := 0; i < len(lines); i++ {
		line := strings.TrimRight(lines[i], " ")
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "":
			flush()
		case strings.HasPrefix(trimmed, "# "):
			flush()
			title := inline(trimmed[2:], dir)
			doc.Blocks = append(doc.Blocks, documents.Title{Text: title})
			if doc.Meta.Title == "" {
				doc.Meta.Title = plain(trimmed[2:])
				doc.Running = title
			}
		case strings.HasPrefix(trimmed, "## "), strings.HasPrefix(trimmed, "### "):
			flush()
			doc.Blocks = append(doc.Blocks, documents.Heading{Text: inline(strings.TrimLeft(trimmed, "# "), dir)})
		case trimmed == "---":
			flush()
			doc.Blocks = append(doc.Blocks, documents.Rule{})
		case strings.HasPrefix(trimmed, "- "), strings.HasPrefix(trimmed, "* "):
			flush()
			doc.Blocks = append(doc.Blocks, documents.Paragraph{Text: "•  " + inline(trimmed[2:], dir)})
		case numbered.MatchString(trimmed):
			flush()
			m := numbered.FindStringSubmatch(trimmed)
			doc.Blocks = append(doc.Blocks, documents.Paragraph{Text: typeset.Isolate(m[1]+".") + "  " + inline(m[2], dir)})
		case strings.HasPrefix(trimmed, "> "):
			flush()
			doc.Blocks = append(doc.Blocks, documents.Paragraph{Text: inline(trimmed[2:], dir), Small: true})
		case strings.HasPrefix(trimmed, "|"):
			flush()
			var rows [][]string
			for ; i < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[i]), "|"); i++ {
				if tableRule.MatchString(strings.TrimSpace(lines[i])) {
					continue
				}
				rows = append(rows, cells(lines[i]))
			}
			i--
			doc.Blocks = append(doc.Blocks, table(rows, dir))
		case image.MatchString(trimmed) && image.ReplaceAllString(trimmed, "") == "":
			flush()
		default:
			paragraph = append(paragraph, trimmed)
		}
	}
	flush()
	return doc
}

func cells(line string) []string {
	parts := strings.Split(strings.Trim(strings.TrimSpace(line), "|"), "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

func table(rows [][]string, dir documents.Direction) documents.Table {
	if len(rows) == 0 {
		return documents.Table{}
	}
	t := documents.Table{}
	width := len(rows[0])
	longest := make([]int, width)
	for _, h := range rows[0] {
		t.Headings = append(t.Headings, inline(h, dir))
	}
	for _, r := range rows {
		for c := 0; c < width && c < len(r); c++ {
			longest[c] = max(longest[c], len([]rune(plain(r[c]))))
		}
	}
	for c := range width {
		t.Widths = append(t.Widths, min(max(longest[c], 6), 60))
	}
	for _, r := range rows[1:] {
		row := make([]documents.Cell, width)
		for c := range width {
			text := ""
			if c < len(r) {
				text = r[c]
			}
			row[c] = documents.T(inline(text, dir))
		}
		t.Rows = append(t.Rows, row)
	}
	return t
}

// plain is a line's text without Markdown: links become their words, emphasis and code marks go, images go.
func plain(s string) string {
	s = image.ReplaceAllString(s, "")
	s = link.ReplaceAllString(s, "$1")
	s = htmlBreaks.ReplaceAllString(s, " ")
	return strings.TrimSpace(emphasis.ReplaceAllString(s, ""))
}

// inline is plain text with, in a right-to-left guide, every Latin-or-digit run isolated left to right.
func inline(s string, dir documents.Direction) string {
	s = plain(s)
	if dir != documents.RTL {
		return s
	}
	return figureRun.ReplaceAllStringFunc(s, typeset.Isolate)
}
